INSERT INTO Trucks (businessName, cuisine, firstName, lastName, email, phone, address, city, state, zip) VALUES ("Tico's Tacos", "Mexican", "Noah", "Glasser", "noah@gmail.com", "4157289976", "555 Mission", "San Francisco", "CA", "941007")
INSERT INTO Trucks (businessName, cuisine, firstName, lastName, email, phone, address, city, state, zip) VALUES ("Fish Dish", "Chinese", "4133284446", "true")
INSERT INTO Trucks (businessName, cuisine, firstName, lastName, email, phone, address, city, state, zip) VALUES ("Jacob's Hoagies", "American", "5107288890", "true")
INSERT INTO Trucks (businessName, cuisine, firstName, middleInitial, lastName, email, phone, address, address2, city, state, zip, approved) VALUES ("The Roasted Pig", "American", "786940392", "true")
INSERT INTO Trucks (businessName, cuisine, phone, approved) VALUES ("Sushi Truck", "Japanese", "4158674930", "true")
INSERT INTO Trucks (businessName, cuisine, phone, approved) VALUES ("Frozen Banana Bonanza", "American", "4159982674", "true")
INSERT INTO Trucks (businessName, cuisine, phone, approved) VALUES ("Ol' Sally May's Grill", "American", "4150982658", "true")
INSERT INTO Trucks (businessName, cuisine, phone, approved) VALUES ("The French Quarter", "French", "4151328853", "true")
INSERT INTO Trucks (businessName, cuisine, phone, approved) VALUES ("Jimmy's Pho Truck", "Vietnamese", "4159877493", "true")
INSERT INTO Trucks (businessName, cuisine, phone, approved) VALUES ("Sajeel's Southern Grill", "Mexican", "4150098375", "true")

INSERT INTO Reviews (truckName, rating, comments) VALUES ("Sajeel's Southern Grill", 4, "This is a great foodtruck")
INSERT INTO Reviews (truckName, rating, comments) VALUES ("Sajeel's Southern Grill", 1, "This is an okay Foodtruck")
INSERT INTO Reviews (truckName, rating, comments) VALUES ("Sajeel's Southern Grill", 5, "BEST RESTURANT EVER")
-- insert many